export const EMOJI_CATALOG: ReadonlyArray<{
  id: string
  name: string
  emojis: ReadonlyArray<{ code: string; name: string }>
}> = [
  {
    id: 'fruits',
    name: 'Fruits',
    emojis: [
      { code: '🍎', name: 'red apple' },
      { code: '🍊', name: 'orange' },
      { code: '🍋', name: 'lemon' },
      { code: '🍇', name: 'grapes' },
      { code: '🍉', name: 'watermelon' },
      { code: '🍓', name: 'strawberry' },
      { code: '🍑', name: 'peach' },
      { code: '🍒', name: 'cherries' },
      { code: '🥝', name: 'kiwi' },
      { code: '🍌', name: 'banana' },
      { code: '🍍', name: 'pineapple' },
      { code: '🥭', name: 'mango' },
      { code: '🫐', name: 'blueberry' },
      { code: '🥥', name: 'coconut' },
      { code: '🍈', name: 'melon' },
    ],
  },
  {
    id: 'animals',
    name: 'Animals',
    emojis: [
      { code: '🐶', name: 'dog' },
      { code: '🐱', name: 'cat' },
      { code: '🐭', name: 'mouse' },
      { code: '🐹', name: 'hamster' },
      { code: '🐰', name: 'rabbit' },
      { code: '🦊', name: 'fox' },
      { code: '🐻', name: 'bear' },
      { code: '🐼', name: 'panda' },
      { code: '🐨', name: 'koala' },
      { code: '🐯', name: 'tiger' },
      { code: '🦁', name: 'lion' },
      { code: '🐮', name: 'cow' },
      { code: '🐸', name: 'frog' },
      { code: '🐵', name: 'monkey face' },
      { code: '🦄', name: 'unicorn' },
    ],
  },
  {
    id: 'food',
    name: 'Food',
    emojis: [
      { code: '🍕', name: 'pizza' },
      { code: '🍔', name: 'hamburger' },
      { code: '🌭', name: 'hot dog' },
      { code: '🍟', name: 'french fries' },
      { code: '🌮', name: 'taco' },
      { code: '🍩', name: 'doughnut' },
      { code: '🍪', name: 'cookie' },
      { code: '🎂', name: 'birthday cake' },
      { code: '🍰', name: 'shortcake' },
      { code: '🧁', name: 'cupcake' },
      { code: '🥞', name: 'pancakes' },
      { code: '🧇', name: 'waffle' },
      { code: '🥨', name: 'pretzel' },
      { code: '🌯', name: 'burrito' },
      { code: '🥐', name: 'croissant' },
    ],
  },
  {
    id: 'vehicles',
    name: 'Vehicles',
    emojis: [
      { code: '🚗', name: 'automobile' },
      { code: '🚕', name: 'taxi' },
      { code: '🚙', name: 'sport utility vehicle' },
      { code: '🚌', name: 'bus' },
      { code: '🚎', name: 'trolleybus' },
      { code: '🏎️', name: 'racing car' },
      { code: '🚓', name: 'police car' },
      { code: '🚑', name: 'ambulance' },
      { code: '🚒', name: 'fire engine' },
      { code: '🚐', name: 'minibus' },
      { code: '🛻', name: 'pickup truck' },
      { code: '🚚', name: 'delivery truck' },
      { code: '🚃', name: 'railway car' },
      { code: '🏍️', name: 'motorcycle' },
      { code: '🚲', name: 'bicycle' },
    ],
  },
  {
    id: 'hearts',
    name: 'Hearts',
    emojis: [
      { code: '❤️', name: 'red heart' },
      { code: '🧡', name: 'orange heart' },
      { code: '💛', name: 'yellow heart' },
      { code: '💚', name: 'green heart' },
      { code: '💙', name: 'blue heart' },
      { code: '💜', name: 'purple heart' },
      { code: '🖤', name: 'black heart' },
      { code: '🤍', name: 'white heart' },
      { code: '🤎', name: 'brown heart' },
      { code: '💗', name: 'growing heart' },
      { code: '💖', name: 'sparkling heart' },
      { code: '💝', name: 'heart with ribbon' },
      { code: '💞', name: 'revolving hearts' },
      { code: '💘', name: 'heart with arrow' },
      { code: '💕', name: 'two hearts' },
    ],
  },
  {
    id: 'sports',
    name: 'Sports',
    emojis: [
      { code: '⚽', name: 'soccer ball' },
      { code: '🏀', name: 'basketball' },
      { code: '🏈', name: 'american football' },
      { code: '⚾', name: 'baseball' },
      { code: '🎾', name: 'tennis' },
      { code: '🏐', name: 'volleyball' },
      { code: '🏉', name: 'rugby football' },
      { code: '🎱', name: 'pool 8 ball' },
      { code: '🏓', name: 'ping pong' },
      { code: '🏸', name: 'badminton' },
      { code: '🥊', name: 'boxing glove' },
      { code: '🥋', name: 'martial arts uniform' },
      { code: '⛳', name: 'flag in hole' },
      { code: '🎳', name: 'bowling' },
      { code: '🏋️', name: 'person lifting weights' },
    ],
  },
  {
    id: 'nature',
    name: 'Nature',
    emojis: [
      { code: '🌸', name: 'cherry blossom' },
      { code: '🌺', name: 'hibiscus' },
      { code: '🌻', name: 'sunflower' },
      { code: '🌹', name: 'rose' },
      { code: '🌷', name: 'tulip' },
      { code: '💐', name: 'bouquet' },
      { code: '🌼', name: 'blossom' },
      { code: '🌵', name: 'cactus' },
      { code: '🌴', name: 'palm tree' },
      { code: '🍀', name: 'four leaf clover' },
      { code: '🌿', name: 'herb' },
      { code: '🍁', name: 'maple leaf' },
      { code: '🌾', name: 'sheaf of rice' },
      { code: '🍂', name: 'fallen leaves' },
      { code: '🪻', name: 'hyacinth' },
    ],
  },
  {
    id: 'faces',
    name: 'Faces',
    emojis: [
      { code: '😀', name: 'grinning face' },
      { code: '😃', name: 'grinning face with big eyes' },
      { code: '😄', name: 'grinning face with smiling eyes' },
      { code: '😁', name: 'beaming face' },
      { code: '😆', name: 'grinning squinting face' },
      { code: '😅', name: 'grinning face with sweat' },
      { code: '🤣', name: 'rolling on the floor laughing' },
      { code: '😂', name: 'face with tears of joy' },
      { code: '🙂', name: 'slightly smiling face' },
      { code: '😊', name: 'smiling face with smiling eyes' },
      { code: '😇', name: 'smiling face with halo' },
      { code: '🥰', name: 'smiling face with hearts' },
      { code: '🤩', name: 'star-struck' },
      { code: '😎', name: 'smiling face with sunglasses' },
      { code: '🥳', name: 'partying face' },
    ],
  },
] as const
